# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e34a3942535bee73e13ee11af2fb07e356b97fa43917c4eb45111eb3bf2d41c8769054e14008c1af307817ad234ab99a861224ac9d25c85a937ac1f08ce7d51b

test:
  secret_key_base: 54ed5f42d908f6acc896409385b407d5a047c88f4dffb1f1318d0c340789175c06a4f9bf2d217f0fb892369d4e6230c3977ed96908695fe6ce383d5b52e07050

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
